### ISSUE TITLE
Login Page not recognized

### ISSUE THREAD

**Issue by jjaquinta** [csaftoiu/yahoo-groups-backup#51]
The login page has changed and when it tries to click on "next" it instead clicks on an advertisement. 
I was able to fix this by changing process_login_page to the following:

```
    def _process_login_page(self):
        """Process the login page."""
        if not self.login_email or not self.password:
            raise ValueError("Detected private group! Login information is required")

        eprint("Processing the log-in page...")

        # email ...
        self.br.fill("username", self.login_email+Keys.RETURN)
        # Wait ...
        time.sleep(2)

        # password ...
        self.br.fill("password", self.password+Keys.RETURN)
        # Wait ...
        time.sleep(2)
```

**Comment by jjaquinta** [comment]
Oh, I also had to change `is_login_page` since, for me, the username entry is split from the password entry.

```
   def _is_login_page(self):
        html = self.br.html
        eprint("Detecting the log-in page...")
        # eprint(html)
        ret = "Enter your&nbsp;email" in html or "Sign&nbsp;in" in html
        eprint("Detected="+str(ret))
        return ret
```

**Comment by nudomarinero** [comment]
Thanks. These changes work for me (in a forked version of @hrenfroe - https://github.com/hrenfroe/yahoo-groups-backup). Provided that you quickly click the OK button in first dialog that appears the script continues correctly.

**Comment by chrisindallas** [comment]
I tried these patches. My Chrome window pops up and goes away after a few seconds. I've tried it with and without --login= and --password= . I'm fine with typing in my login credentials, but I need more time. This evidently isn't the time.sleep() above, because I changed those to 30 seconds and no different. Any ideas?

**Comment by hrenfroe** [comment]
@chrisindallas Have you tried my fork at https://github.com/hrenfroe/yahoo-groups-backup ? I've implemented a solution to the issues with recognizing and autofilling the login pages, and I have it working without manual intervention. Check it out and feel free to open a separate issue there if you're still having trouble.

**Comment by JustinCEO** [comment]
hi @hrenfroe, i tried using your fork with the argument `--driver=chrome` (in order to deal with another error I had) and I'm getting the error message "ValueError: Detected private group! Login information is required." i edited the settings.yaml.template file with my account info. any ideas? 

if i don't use  `--driver=chrome`, firefox opens to a blank page and nothing happens, and i get the error message 

```selenium.common.exceptions.WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.```


if i do use  `--driver=chrome`, chromium at least gets to the yahoo login page :)

**Comment by JustinCEO** [comment]
oh wow, i figured it out, i forgot to remove "template" from the settings.yaml.template file name, haha

**Comment by csaftoiu** [comment]
@hrenfroe if you make a PR i'll merge it, using your version now to dump my private group :) works fine once i click the initial "OK"

**Comment by hrenfroe** [comment]
PR opened :+1:

**Comment by csaftoiu** [comment]
Resolved by https://github.com/csaftoiu/yahoo-groups-backup/pull/54
